### ISSUE TITLE
The IP header is of variable size

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#11]
The code of Gatekeeper assumes that IP headers always have the same size, but due to options, the headers can vary in size. Moreover, the mechanism is different for IPv4 and IPv6.

The code that parses packets must deal with the variable size. Perhaps, DPDK has some functions to help to deal with it.

**Comment by cjdoucette** [comment]
As a part of this, we should find out what happens when IPv6 packets with a variable header size are passed through filters. I think the only IPv6 filter we have is the ntuple filter for IPv6 BGP packets, which will be active once the CPS block is merged.

Same issue for the ACL for IPv6 packets: how can we compare IPv6 packets with variable headers against a fixed set of ACL rules?

**Comment by AltraMayor** [comment]
I recommend to investigate how the Linux kernel solves this problem. This would provide a reference point for our final implementation.

**Comment by AltraMayor** [comment]
Pull request #48 addresses this issue.
