### ISSUE TITLE
Amazon ENAs do not report link speed

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#120]
Amazon's Elastic Network Adapters do not report interface link speed:

http://mails.dpdk.org/archives/stable/2018-July/008584.html

https://github.com/amzn/amzn-drivers/issues/61

This is because the bandwidth is per-instance and not per-ENA.

However, Gatekeeper servers require knowing the speed of back interface in order to calculate the refill rate of the token bucket algorithm in the Solicitor block.

**Comment by cjdoucette** [comment]
One option to deal with this issue is to allow a configuration option in the Solicitor block to override the reported link speed if it is read as 0. This allows the operator to estimate the link speed and input it to Gatekeeper for calculating the token bucket algorithm variables.

**Comment by AltraMayor** [comment]
Wow, this is super important because it means that a DDoS attack at the front network of a Gatekeeper server depoyed on an Amazon VM reduces the bandwidth of the back network, that is, there is no isolation between front and back network! This may causes surprises, for example, the Gatekeeper may not receive a policy decision due to the DDoS at the front. Please document this fact in Gatekeeper's wiki since whoever deploys Gatekeeper on Amazon must be aware of it.

On the practical side, we do need to have a configuration option as you said. But I suggest it work in a different way:
1. If this new option is not set, Gatekeeper will fail to initialize. The error message should explain the problem (i.e. the interface doesn't have bandwidth information) and point on how to set the bandwidth for the SOL block.
2. When the new option is set, it defines the bandwidth of the request channel. Example: 1Gbps. That is, it doesn't use percentage, it doesn't define the bandwidth of the interface. The reason for that is that operators will need to figure out the bandwidth somehow, and having to retrofit that information into an interface plus percentage to make it fit the current set up is just making things more complicated.

**Comment by AltraMayor** [comment]
Does the NIC drive in KVM have the same issue? What's it the driver in KVM?

**Comment by cjdoucette** [comment]
No, the virtio driver in KVM does not have the same restriction.

**Comment by cjdoucette** [comment]
#132 solved this issue.
