### ISSUE TITLE
Fib deadlock due to a Lua error

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#163]
Both `list_fib_for_lua()` and `list_neighbors_for_lua()` in file `gk/fib.c` hold Fib lock `gk_conf->lpm_tbl.lock` while a Lua callback is called potentially multiple times. If the Lua callback or any other Lua error is raised while the lock is held, `list_fib_for_lua()` and `list_neighbors_for_lua()` won't have a chance to unlock before returning to Lua. Thus, the lock is forever locked.

The C function that `list_fib_for_lua()` and `list_neighbors_for_lua()` receive as parameter and call under the lock must be called using `lua_cpcall()`, so if a Lua error is raised, the code can release the lock before raising the error again.

**Comment by mengxiang0811** [comment]
Since the functions ``list_ipv4_fib_entries(), list_ipv6_fib_entries(), list_ipv4_if_neighbors(), list_ipv6_if_neighbors()`` all have the parameter ``struct gk_lpm *ltbl``, which has the needed lock information. I think an alternative solution is to replace ``lua_call(l, 2, 1);``  with ``lua_pcall(l, 2, 1, 0);`` and then if error happens, the code can release the lock and raise the error. If so, we can have much less code change.

**Comment by AltraMayor** [comment]
Nice approach! Yes, pushing the lock acquisition and release all the way down to the iteration is simpler.
