### ISSUE TITLE
How stable or production ready is gatekeeper? 

### ISSUE THREAD

**Issue by CheyenneForbes** [AltraMayor/gatekeeper#189]

**Comment by AltraMayor** [comment]
Hi @CheyenneForbes,

We are currently working on deploying Gatekeeper in production. You can track our progress at this milestone: [First deployment](https://github.com/AltraMayor/gatekeeper/milestone/3). We are missing a lot of tests and documentation before the deployment and releasing the first stable version.

**Comment by CheyenneForbes** [comment]
Hi @AltraMayor, thanks for responding. Would you say the aim of Gatekeeper is to be a comparable/competitive alternative to F5 Networks and Fortinet's software/hardware solutions?

**Comment by AltraMayor** [comment]
Yes, Gatekeeper is comparable to DDoS solutions in the market. But Gatekeeper does not try to be compatible or work the way they do. Gatekeeper is new in the sense that it implements a capability system (see the original definition of these systems [here](https://dl.acm.org/citation.cfm?id=972382)). Gatekeeper supports IPv4 and IPv6 networks. We expect that Gatekeeper will be competitive against the current solutions, but until we have hard data, we cannot promisse much.

**Comment by AltraMayor** [comment]
We have come a long way until here. We expect to finally mark the code on the repository as production-ready sometime in November 2020. This is mostly a conservative official release since Gatekeeper has already been used in production as Alexander Pavlov, deputy director for network operations at [Mail.ru](https://mail.ru/), presented at the conference [NextHop 2020](https://yandex.ru/promo/events/generated/nexthop2020/) on October 12th, 2020. [Watch the presentation in English](https://www.youtube.com/watch?v=IZEDxxJYVdo&t=9097s). A [1-Tbps deployment](https://github.com/AltraMayor/gatekeeper/issues/417#issuecomment-702163114) is already underway!

**Comment by AltraMayor** [comment]
Gatekeeper 1.0.0 is official!

It is embarrassing to read today my previous promises above. We've faced way more surprises than anyone in our team had predicted. But, today, we stand with John Lennon to say that "a dream you dream together is reality.”
