### ISSUE TITLE
Packaging Gatekeeper

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#194]
Having a Debian package to deploy Gatekeeper is essential in production. Besides the normal things expected of a package (i.e. creating a constrained user and required folders, copying files, and adjusting permissions), one has to write an initialization script for Gatekeeper.

This issue depends on issue #140.

**Comment by AltraMayor** [comment]
While BIRD is part of our source tree, we need a package for our version of BIRD as well. Once our patches are merged upstream, we'll no longer need to have BIRD inside our source tree and the BIRD package found in distros will suffice.

**Comment by andrenth** [comment]
I have a working package but before submitting I want to make sure this directory tree is fine and that I haven't forgotten anything, since there's no `make install` target for Gatekeeper:

```
.
├── etc
│   └── gatekeeper
│       ├── cps.lua
│       ├── dylib.lua
│       ├── dyn_cfg.lua
│       ├── example_of_dynamic_config_request.lua
│       ├── gatekeeper.lua
│       ├── gatekeeper_config.lua
│       ├── ggu.lua
│       ├── gk.lua
│       ├── gt.lua
│       ├── lls.lua
│       ├── net.lua
│       ├── policy.lua
│       ├── policylib.lua
│       └── sol.lua
├── lib
│   └── systemd
│       └── system
│           └── gatekeeper.service
├── usr
│   ├── sbin
│   │   ├── gatekeeper
│   │   ├── generate_if_map
│   │   └── gkctl
│   └── share
│       ├── doc
│       │   └── gatekeeper
│       │       ├── changelog.gz
│       │       └── copyright
│       └── lintian
│           └── overrides
│               └── gatekeeper
└── var
    └── log
        └── gatekeeper
```

The `generate_if_map` command is run on post-install time to generate `/etc/gatekeeper/if_map.lua`.

The systemd service file's contents follow below.

```
[Unit]
Description=Gatekeeper DDoS protection system
After=network.target

[Service]
EnvironmentFile=-/etc/gatekeeper/envvars
ExecStartPre=/bin/mkdir -p /var/run/gatekeeper
ExecStart=/usr/sbin/gatekeeper $GATEKEEPER_ARGS
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

**Comment by cjdoucette** [comment]
Are there any naming conventions for folders like `conf` or `examples` that we could use for some of the files that are in `etc/gatekeeper`?

`example_of_dynamic_config_request.lua` and `policy.lua` are examples. `policylib.lua` and `dylib.lua` are libraries. All the other `.lua` files are configuration files.

Just curious. Otherwise, looks good to me.

**Comment by cjdoucette** [comment]
By the way, the version of BIRD that is found in our source tree may still be changed as we merge the final patches in Gatekeeper for interacting with it. I even made a small modification to one of the patches in the `bird` submodule today. So if possible, I would wait until we finish #56 before packaging that.

**Comment by andrenth** [comment]
The convention is that configuration files go in `/etc`. I’ll move the library files to a better place, probably`/usr/share/gatekeeper`.

**Comment by andrenth** [comment]
Also I’ve been working on the gatekeeper-birds package as a sub-package of gatekeeper but that ties them to the same version number, and it might make more sense to use the same version as bird itself?

In that case the PR for gatekeeper-bird would have to be made against the patched bird repo and not this one.

**Comment by andrenth** [comment]
This is the directory structure I have now:

```
.
├── etc
│   └── gatekeeper
│       ├── cps.lua
│       ├── dyn_cfg.lua
│       ├── gatekeeper.lua
│       ├── gatekeeper_config.lua
│       ├── ggu.lua
│       ├── gk.lua
│       ├── gt.lua
│       ├── lls.lua
│       ├── net.lua
│       └── sol.lua
├── lib
│   └── systemd
│       └── system
│           └── gatekeeper.service
├── usr
│   ├── sbin
│   │   ├── gatekeeper
│   │   ├── generate_if_map
│   │   └── gkctl
│   └── share
│       ├── doc
│       │   └── gatekeeper
│       │       ├── changelog.gz
│       │       ├── copyright
│       │       └── examples
│       │           ├── example_of_dynamic_config_request.lua.gz
│       │           └── policy.lua.gz
│       ├── lintian
│       │   └── overrides
│       │       └── gatekeeper
│       └── lua
│           └── 5.1
│               └── gatekeeper
│                   ├── dylib.lua
│                   └── policylib.lua
└── var
    └── log
        └── gatekeeper
```

As you can see, `dylib.lua` and `policylib.lua` are installed in `/usr/share/lua/5.1` so that Lua's `require` is able to find them automatically.

I've actually put them under a `gatekeeper` directory, which would require changing the requires as below:

```
- local policylib = require("policylib")
+ local policylib = require("gatekeeper/policylib")
```

Would this change be OK? I think it's nice because it "namespaces" the gatekeeper libraries, but I can just install the files directly into `/usr/share/lua/5.1` if you prefer.

The sample configurations are installed in `/usr/share/doc/gatekeeper/examples`. They're gzipped as per Debian's packaging standards.

One downside of the current package is that I must list all Lua files to be installed in manually, because currently libraries, configurations and examples live in the same directory. What do you think about reorganizing them as below?

```
lua
├── cps.lua
├── dyn_cfg.lua
├── gatekeeper.lua
├── gatekeeper_config.lua
├── ggu.lua
├── gk.lua
├── gt.lua
├── lls.lua
├── net.lua
├── sol.lua
├── examples
│   ├── example_of_dynamic_config_request.lua
│   └── policy.lua
└── gatekeeper
     ├── dylib.lua
     └── policylib.lua
```

**Comment by AltraMayor** [comment]
@andrenth, I like your suggestion to put the Lua libraries under the `gatekeeper` folder, it makes the installation clean. You can go ahead and issue a pull request to update the `require()`s.

You can also update the `lua` folder. I just ask to ensure that Gatekeeper can be run after compilation to keep testing and development simple.

**Comment by AltraMayor** [comment]
@andrenth, I realized today that we are missing the folder `/var/run/gatekeeper` that will hold the Unix socket used to communicate with the Dynamic configuration block. This folder will be empty, but we package should create it.

**Comment by andrenth** [comment]
@AltraMayor Creating files in /var/run is against the Debian packaging policy: https://lintian.debian.org/tags/dir-or-file-in-var-run.html

What I did was specifying a pre-start command in the systemd unit that creates the directory.

**Comment by AltraMayor** [comment]
Your solution is fine. I'm glad we have someone, namely you, making sure that our packages comply with all the rules and guidelines.

**Comment by andrenth** [comment]
Well, the lintian tool finds all the packaging bugs for me, so I can’t really take the full credit :)

**Comment by andrenth** [comment]
PR #218 created for this.
