### ISSUE TITLE
Logging basic measurements 

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#198]
Right now, if Gatekeeper were deployed and worked flawlessly, there would be no easy way to know how much traffic it has approved and how much traffic it dropped. In other words, we couldn't argue that Gatekeeper was protecting or doing anything for the deployer. Measurement is a big topic and fully addressing it is outside of the scope of this issue. The goal of this issue is for GK blocks to periodically log how much traffic it has forwarded through the granted channel, request channel, and how much it has dropped because it has been rejected. Each of these measurements should include size (i.e. accumulated packet size) and the number of packets.

**Comment by mengxiang0811** [comment]
As the statistics over the traffic processed by GK blocks is on the critical path, should we do the statistics on a per-block basis or global basis over all the blocks or use a separate collector block?

**Option#1**: it doesn't need the synchronization across all the GK blocks, however, it cannot see the overall statistics.

**Option#2**: it does need synchronization, which may degrade the performance.

**Option#3**: Let each GK block do the statistics independently, and then after a period each block sends its statistics to a collector block via ring, so that the collector block will do the statistics.

**Comment by AltraMayor** [comment]
We should embrace Option#1 for now. That is, each instance of the GK blocks accounts for the packets in its own structure and occasionally logs the measurements and resets its structure. The reason for this choice is twofold: it is very simple and avoids lock contention (ignoring the occasional log synchronization). Of course, a script will be needed to read the log and present the statistics in a friendly way, but this script can be written later. @andrenth or someone at Digirati may even help with writing this script.

We are going to refine this feature in the future, but Option#1 is enough for the first depoyment.
