### ISSUE TITLE
Error setting up Gatekeeper

### ISSUE THREAD

**Issue by mengxiang0811** [AltraMayor/gatekeeper#203]
When trying to obtain the sources of the dependencies, there is an error message:
```
warning: redirecting to https://github.com/cjdoucette/bird.git/
warning: redirecting to https://github.com/cjdoucette/bird.git/
error: Server does not allow request for unadvertised object 29729b912ad4f974ce4787c0e5d4abfc49ff75ff
Fetched in submodule path 'dependencies/bird', but it did not contain 29729b912ad4f974ce4787c0e5d4abfc49ff75ff. Direct fetching of that commit failed.
```

**Comment by cjdoucette** [comment]
This is just because I needed to update the bird submodule. Once pull request #200 is accepted, the submodule will be updated with the correct commit hash and it will work once again.

Until then, you can change directory into the bird folder and fetch the correct remote repository. You might have to do this for the other submodules as well if the command to fetch them all at once is failing.

**Comment by AltraMayor** [comment]
Since pull request #200 was merged today, this issue is solved.
