### ISSUE TITLE
Failed to config port

### ISSUE THREAD

**Issue by ZhongqiXiao** [AltraMayor/gatekeeper#217]
When I run gatekeeper,it stopped,and the log is:
```
GATEKEEPER: main: cycles/second = 2394463098, cycles/millisecond = 2394463, picosec/cycle = 417
GATEKEEPER CPS: init_kni: /data/gatekeeper/dependencies/dpdk/build/kmod/rte_kni.ko already inserted
GATEKEEPER: net: port 0 (0000:02:00.2) on the front interface only supports RSS hash functions 0x38d34, but Gatekeeper asks for 0xa38c
GATEKEEPER: net: port 1 (0000:06:00.0) on the back interface only supports RSS hash functions 0x38d34, but Gatekeeper asks for 0xa38c
Ethdev port_id=1 nb_rx_queues=5 > 4
GATEKEEPER: net: failed to configure port 1 (0000:06:00.0) on the back interface (err=-22)
Device with port_id=0 already stopped
```
What is `0xa38c` ? How can I solve the problem? I'll appreciate if you give me some advice.

**Comment by AltraMayor** [comment]
The code `0xa38c` are bits that specify RSS hash functions in hardware for optimal performance. This only matter in a real deployment. It's not what's holding Gatekeeper to boot up, though.

The issue is present at this line: `Ethdev port_id=1 nb_rx_queues=5 > 4`. It means that your NIC on the back interface only supports 4 receiving queues, but Gatekeeper is configured to need 5.

Gatekeeper does not support a large number of NICs because this would impact its peak performance while processing packets, what is critical during a DDoS. If it's a real machine, try another NIC. If it's a VM, you can try another kind of instance or virtualization technology. A workaround is to comment out the CPS block or to set variable `n_lcores` to 1 in file `gatekeeper_config.lua`. Commeting our the CPS block won't allow you to run a BGP speaker, but it's okay for initial testing. Set variable `n_lcores` to 1 have a single GK block processing traffic.

**Comment by ZhongqiXiao** [comment]
Thank you for advicing!
I change NIC to Inter82599, run `build/gatekeeper` , and it stopped. The log is:
```
GATEKEEPER: main: cycles/second = 3491953093, cycles/millisecond = 3491953, picosec/cycle = 286
GATEKEEPER CPS: init_kni: /data/gatekeeper/dependencies/dpdk/build/kmod/rte_kni.ko already inserted
GATEKEEPER: net: port 0 (0000:02:00.0) on the front interface only supports RSS hash functions 0x38d34, but Gatekeeper asks for 0xa38c
GATEKEEPER: net: port 0 (0000:02:00.0) on the back interface only supports RSS hash functions 0x38d34, but Gatekeeper asks for 0xa38c
GATEKEEPER: net: calculate_net_config_para: total_pkt_burst (front) = 1216 packets, total_pkt_burst (back) = 192 packets, gatekeeper_num_lcores = 6 lcores, gatekeeper_total_rx_desc = 2688 descriptors, gatekeeper_total_tx_desc = 1152 descriptors, gatekeeper_max_num_pkt = 8320 packets, gatekeeper_num_mbuf = 16383 packets, gatekeeper_per_lcore_cache_size = 381 mbufs.
KNI: pci: 02:00:00 	 8086:10fb
Device with port_id=0 already stopped
KNI: pci: 02:00:00 	 8086:10fb
Device with port_id=0 already started
GATEKEEPER: net: EtherType filters are supported on the front iface
GATEKEEPER: net: ntuple filters are supported on the front iface
Device with port_id=0 already started
GATEKEEPER: net: EtherType filters are supported on the back iface
GATEKEEPER: net: ntuple filters are supported on the back iface
ixgbe_add_del_ethertype_filter(): ethertype (0x0806) filter exists.
GATEKEEPER: net: other errors that depend on the specific operations implementation on port 0 for adding an EtherType filter for 0x806
Device with port_id=0 already stopped
```
How can I solve the problem?

**Comment by AltraMayor** [comment]
The log entry `ixgbe_add_del_ethertype_filter(): ethertype (0x0806) filter exists.` means that the LLS block cannot install an Ethernet filter for ARP (i.e. 0x0806) because such filter already exists. Based on the log entry `GATEKEEPER CPS: init_kni: /data/gatekeeper/dependencies/dpdk/build/kmod/rte_kni.ko already inserted`, I guess that you have tried to boot Gatekeeper, failed, tried again, and got this failure. I think our code is not clearing the filters when booting after a crash.

To test this hypothesis, could you reboot the machine you are using to test Gatekeeper and try to boot Gatekeeper again? If rebooting the machine avoids the problem above, I'll open an issue to address this condition.

**Comment by ZhongqiXiao** [comment]
Thank you very much! It works.

**Comment by AltraMayor** [comment]
Thank you for your report. I've opened issue #221 to enable Gatekeeper to forgo the need to reboot the machine to start again.
