### ISSUE TITLE
Supporting a 1Gbps NIC

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#22]
Supporting to a 1Gbps NIC is important for interconnecting with legacy network meshes. This is especially critical for Grantor servers. This feature would also enable people to test Gatekeeper in cheap, commonplace test environments.

A suggestion on how to do this is to implement a virtual NIC over a real dummy NIC. This virtual NIC only has to implement the filters Gatekeeper needs. Moreover, this virtual NIC only has to reach 1Gbps of throughput, for anything above that the installer has to acquire one of the NICs Gatekeeper supports.

**Comment by cjdoucette** [comment]
The DPDK developers are attempting to address a related problem whose solution will help us here. Essentially, DPDK applications have to be very aware of the underlying hardware capabilities, especially in terms of what filters are available in the hardware and driver.

A new library in DPDK, the [generic flow API](http://dpdk.org/doc/guides/prog_guide/rte_flow.html), will be released in February. Motivation and much more information is available here: http://dpdk.org/ml/archives/dev/2016-August/045383.html

This will be a higher-level interface that will allow applications to express what kinds of flows it is interested in, and this library will perform the mapping from the flow down to the filters on a per-device basis.

Therefore, once this library is available, we should be able to support 1Gbps NICs and 10Gbps NICs simultaneously with the same code.

**Comment by AltraMayor** [comment]
Hi Cody,

That would be a godsend at the right time! But reading section 8.7 of the [generic flow API](http://dpdk.org/doc/guides/prog_guide/rte_flow.html) doesn't inspire confidence since "no known implementation supports all the described features" AND "unsupported features or combinations are not expected to be fully emulated in software by PMDs for performance reasons".

" and

**Comment by AltraMayor** [comment]
A solution to support virtually any NIC is to implement an IPv4 filter like we did for IPv6. Thus, whenever a given hardware filter is not supported, the block installing the filter would fall back to use the IPv4 filter. This would lower the requirement on NICs to just supporting RSS and multiqueues, what is a low bar.

**Comment by cjdoucette** [comment]
There appears to be a single 1 Gbps NIC that supports DPDK and the hardware features that Gatekeeper needs: the Intel 82576 (http://www.intel.com/content/dam/www/public/us/en/documents/datasheets/82576eb-gigabit-ethernet-controller-datasheet.pdf). In particular, it supports RSS, EtherType filters, and 5-tuple filters.

Amazon link here: https://www.amazon.com/Dual-port-Gigabit-Ethernet-Adapter-E1G42ET/dp/B00P26UP5W

It's worth noting that it only supports eight 5-tuple filters, though, compared to our 82599 NIC which has 128 such filters. Currently, Gatekeeper only requires six 5-tuple filters (two for the GK-GT Unit block and four for the CPS block).

There are other 1 Gbps NICs that come close to supporting our requirements. For example, the 82580, I210, I211, and I350 all have support for RSS and EtherType filters. Although they don't support 5-tuple filters, they do support flexible filters, which allow the first 128 bytes of the packet to be matched against a filter. However, in packets with long IP headers (those that include IP options), the L4 header may be outside of the first 128 bytes. Additionally, since the IP header can vary in length, we would need to install flexible filters for all possible variable lengths. For these reasons, the flexible filter is likely not a good substitute for the 5-tuple filters, and therefore these NICs are not sufficient.

**Comment by cjdoucette** [comment]
I think we should leave this issue open until we are able to test Gatekeeper with a 82576 NIC.

**Comment by cjdoucette** [comment]
Gatekeeper runs with the 82576 NIC installed.

On our server, its ports are enp8s0f0 and enp8s0f1, which are connected to ports ens2f1 and ens2f2 respectively.

**Comment by AltraMayor** [comment]
That's great news.

We need now to focus on the IPv4 filter to lower the requirements to RSS and multiqueues in order to be able to run Gatekeeper on AWS.

**Comment by AltraMayor** [comment]
Support to ENA driver to enable Gatekeeper on Amazon AWS is being worked out in pull request #54.

**Comment by AltraMayor** [comment]
Pull request #54 was merged. From now on, Gatekeeper only requires RSS and multiqueues. Therefore, Gatekeeper supports cheap NICs and AWS.
