### ISSUE TITLE
Supporting an initialization after a crash

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#221]
When Gatekeeper crashes or abruptly finishes due to a configuration error during initialization, the network interfaces are left with the setup that was done until then. This is a problem because when Gatekeeper is booting again, it may get errors due to this previous setup; see issue #217 for an example. Another possible situation is when the interfaces were previously set up for another DPDK application and Gatekeeper is called. This situation can lead to unexpected conditions all over the code and could be hard to diagnosticate.

A possible solution is to call [`rte_eth_dev_reset()`](https://doc.dpdk.org/api/rte__ethdev_8h.html#a2d1e21461d6316d4378e5b530c3e0ef9) on the network ports during the initialization of Gatekeeper to clear any lingering setup.

**Comment by cjdoucette** [comment]
I set up a separate dummy program to add an EtherType filter, and ran two instances of that program and used the same interface for each instance. They were both able to run at the same time without seeing the issue in #217. It was only when I ran one instance of this program with code that had back-to-back attempts to add the EtherType filter that I received this message.

This leads me to believe that even if a Gatekeeper instance fails, when it starts again there shouldn't be any issues with interface configuration. The only issue should arise when we attempt to repeatedly add filters to the same interface without resetting (or bring up and down) the interface in question.

I then tried running Gatekeeper with both the front and back set to use the same interface and was able to reproduce the error in #217. I think this misconfiguration was the underlying issue.

I was even able to run two Gatekeeper instances at the same time with the same interfaces (though I had to disable the CPS block in one of them because there is a lock on the KNI subsystem). I'm not saying that this is a valid usage of Gatekeeper because we do not know how the system would behave (which instance would packets get delivered to?), but the point is that there was no conflict in trying to add filters to the interfaces.

**Comment by AltraMayor** [comment]
Thank you for this careful investigation.

I think we should have Lua code that gets `front_ports` and `back_ports` (Lua variables in `net.lua`), maps each name in these arrays to its respective PCI address, and check if the intersection of both arrays is not empty. In spite of the mapping to PCI addresses, the error message, if the intersection is not empty, should give the friendly name of the interfaces and their mappings. Thus, one can identify misconfigured `if_map.lua` files. This patch is enough to close this issue.
