### ISSUE TITLE
Where to download Debian packages for Gatekeeper？

### ISSUE THREAD

**Issue by sweird1** [AltraMayor/gatekeeper#254]
hi @AltraMayor
I refer to here https://github.com/AltraMayor/gatekeeper/releases, and did not find the relevant package, where can I download, thank you.

**Comment by AltraMayor** [comment]
Hi @sweird1,

We've updated the README file with that link before releasing the packages because we are writing all the documentation for the coming release. We are close to having a release candidate, but we are missing some issues. You can track our progress listing milestone [First deployment](https://github.com/AltraMayor/gatekeeper/milestone/3).

Thank you for your interest. I'll keep this issue open until we publish the first packages. Thus, you will receive a notification when we the packages are out.

**Comment by sweird1** [comment]
> Hi @sweird1,
> 
> We've updated the README file with that link before releasing the packages because we are writing all the documentation for the coming release. We are close to having a release candidate, but we are missing some issues. You can track our progress listing milestone [First deployment](https://github.com/AltraMayor/gatekeeper/milestone/3).
> 
> Thank you for your interest. I'll keep this issue open until we publish the first packages. Thus, you will receive a notification when we the packages are out.

Thank you very much , I'm  looking forward to the new release.

**Comment by AltraMayor** [comment]
Hi @sweird1,

After many hoops we had to go through, we've finally released the packages. Notice that this is the first release candidate (RC1) of version 1.0.0, not the final release. But we expect to see small changes from now on until the final release. In fact, we are going to use the RC1 to make the first deployment. It's from this first deployment that we expect to get most of the feedback for the final release.
