### ISSUE TITLE
Add support for VLAN tags

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#28]
Although supporting VLAN tags is essential only at the front interface of Gatekeeper servers due to network requirements of IXes, this feature should be available on both interfaces and for Grantor servers as well in order to keep the network code as symmetric as possible.

The code should use hardware acceleration where it's available, but be able to do all in software if not. The reason for this is to help with issue #22 .

**Comment by cjdoucette** [comment]
Since most DPDK NICs (including the Intel 82599) don't include hardware support for VLAN tag insertion (they only include support for stripping VLAN tags in hardware), this issue is going to be fulfilled completely in software. If and when hardware support for VLAN insertion becomes available, we can revisit this issue.

The reason that we don't want to only use hardware support for VLAN stripping is that we will then have to move the bytes of the packet around to insert a VLAN tag before transmission. Instead, it's more efficient to just keep the ingress VLAN tag on the packet and simply overwrite it before transmission.

**Comment by AltraMayor** [comment]
This issue is being addressed in pull request #49.
