### ISSUE TITLE
BPF program granted.c triggers capability renewal every packet

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/gatekeeper#325]
The program in `bpf/granted.c` is sending each granted packet with priority 2, indicating that the capability should be renewed.

One potential reason for this is that the field `state->renewal_step_cycle` does not seem to be correctly set in `granted_init()`. You can see this when logging the flow state:

```
flow: gk: log the flow state [state: GK_BPF (3), expire_at: 29bbf1b3b2ae32, program_index=0, cookie=  29bbcec6feacc4               a            27ff  29bbcec6feacc4               0               0               0               0, grantor_ip: 172.31.3.117] in the flow table at print_flow_state with lcore 1 for the flow with IP source address 172.31.0.175, and destination address 172.31.3.200
```

Note that the first field of the cookie is `budget_renew_at`, the second field is `tx_rate_kb_cycle`, the third field is `budget_byte`, the fourth field is `send_next_renewal_at`, and the fifth field (which is 0) is supposed to be `renewal_step_cycle`.

Note that `granted_init()` function in `bpf/granted.c` seems to set the field, but printing the flow state after `gk_init_bpf_cookie()` is called reveals it does not seem to be properly set.

Note also that the `budget_renew_at` value and the `send_next_renewal_at` value at the same here, despite the policy indicating that the first renewal message should be sent after 50 seconds:

```
local function dcs_default(policy)
        return policylib.decision_granted(policy,
                10,     -- tx_rate_kb_sec
                60,     -- cap_expire_sec
                50000,  -- next_renewal_ms
                1000)   -- renewal_step_ms
end
```

I wonder whether there is a bug in `granted_init()`, which seems to be using the cookie simultaneously for the parameters as well as the state.

**Comment by cjdoucette** [comment]
A secondary issue to note here is that flows can get effectively a higher rate than they are permitted by the policy if the capability renewal value is set too low, since renewing the capability refills their budget completely.

**Comment by AltraMayor** [comment]
Notice that `granted_init()` copies `params` before editing the `state`: `struct granted_params params = *(struct granted_params *)cookie;`. So I don't think that is the bug.

Some ideas to gather information:
1. Setting a breakpoint at the call of `gk_init_bpf_cookie()` and print the cookie before and after the call. If you compile Gatekeeper with debug information, you can do it inside of the debugger.

2. Creating a parallel flow using the original granted state and printing that flow state as well. This would help us to compare the values of the original granted state against the BPF granted state.

3. At this point, I'm guessing that the bug is in the GGU protocol. So walking through `ggu_policy_iterator()` with a debugger could help.

> A secondary issue to note here is that flows can get effectively a higher rate than they are permitted by the policy if the capability renewal value is set too low, since renewing the capability refills their budget completely.

I don't deny that the traffic is not being rated, but the justification seems off. `granted_pkt()` only sends packets out if there's a budget for it. And renewing a capability doesn't affect the budget.

**Comment by AltraMayor** [comment]
According to the flow you printed out, `tx_rate_kb_cycle` is properly set to 10. But it shows that `budget_byte` is 10239, that is 10 * 1024 - 1. This means that the packet has a single byte. So the line `pkt_len = pkt_ctx_to_pkt(ctx)->pkt_len;` in `granted_pkt()` seems to be seeing something wrong. A way to debug here is to set a breakpoint at `pkt_ctx_to_pkt()` and check the field `pkt_len` then.


flow: gk: log the flow state [state: GK_BPF (3), expire_at: 29bbf1b3b2ae32, program_index=0, cookie=  29bbcec6feacc4               a            27ff  29bbcec6feacc4               0               0               0               0, grantor_ip: 172.31.3.117] in the flow table at print_flow_state with lcore 1 for the flow with IP source address 172.31.0.175, and destination address 172.31.3.200

**Comment by cjdoucette** [comment]
Regarding the value of `budget_byte`: sorry, but that is an artifact of some changes that I made to the code for debugging purposes. I was trying to figure out the execution path in `granted_pkt()`, so I would subtract a byte here or there to see which conditional statements were being triggered.

I'll try your suggestions, thanks!

**Comment by AltraMayor** [comment]
Another possibility to explain the bug is that the BPF program is not getting the correct values of `cycles_per_sec` and `cycles_per_ms`. This can be indirectly checked during the initialization of the cookie. For example, if the BPF program is seeing `cycles_per_ms` as zero, it explains `renewal_step_cycle` being zero.

**Comment by AltraMayor** [comment]
Perhaps the following patch fixes the bug:
```
michel@xia1:~/git/gatekeeper$ git diff include/gatekeeper_flow_bpf.h
diff --git a/include/gatekeeper_flow_bpf.h b/include/gatekeeper_flow_bpf.h
index fcc061c..035cd45 100644
--- a/include/gatekeeper_flow_bpf.h
+++ b/include/gatekeeper_flow_bpf.h
@@ -106,8 +106,8 @@ struct gk_bpf_pkt_ctx {
 #endif
 
 /* Symbols available to the BPF functions init() and pkt(). */
-GK_BPF_INTERNAL uint64_t cycles_per_sec;
-GK_BPF_INTERNAL uint64_t cycles_per_ms;
+extern uint64_t cycles_per_sec;
+extern uint64_t cycles_per_ms;
 
 /* Symbols available to the BPF function init(). */
 GK_BPF_INTERNAL struct gk_bpf_cookie *init_ctx_to_cookie(
```

**Comment by cjdoucette** [comment]
The patch you proposed fixes the issue! I will create a pull request.
