### ISSUE TITLE
Fail to enqueue requests to SOL's ring

### ISSUE THREAD

**Issue by mengxiang0811** [AltraMayor/gatekeeper#374]
When doing the performance evaluation, I occasionally found that the SOL block sometimes fails to enqueue all the requests to its ring. Some example outputs are shown below:

```
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 12 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 4 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 28 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 4 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 16 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 28 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
```

**Comment by AltraMayor** [comment]
Could you count the number of similar log lines and describe the test conditions (e.g. number of GK blocks, flow table size)?

**Comment by mengxiang0811** [comment]
For all our test conditions (i.e., ``1,2,3`` lcores and ``2^15,2^20,2^25`` flow entries), it got similar logs. For 1 lcore with 2^15 flow entries, there are 10 similar log lines, for 3 lcores with 2^25 flow entries, there are 250 lines.

**Comment by AltraMayor** [comment]
I don't think this issue is a bug. The ring between GK blocks and the SOL block is intentionally limited to avoid having too many packets waiting to be placed on the priority queue. The log messages are just reporting that the SOL block cannot keep up with the packets that are being sent to it. This is a characteristic of our evaluation, in which the attacker spoofs all source addresses. Under regular conditions, only 5% of the packets would go to the SOL block. Having a small number of log entries during such an attack is okay.

This will become a performance issue in large deployments. In these deployments, optimization of the code of the SOL block may not be enough, and we may have to have multiple SOL blocks to spread the load between multiple cores. For this reason, I'm moving this issue to the milestone "100+ Gbps deployments".
