### ISSUE TITLE
Configuration Example

### ISSUE THREAD

**Issue by suedadam** [AltraMayor/gatekeeper#39]
Any sort of examples for the config would be helpful. Planning to take some benchmarks of this.

**Comment by AltraMayor** [comment]
Hi @suedadam,

It's too early in the development to provide examples since Gatekeeper is not running yet. We're working on our first milestone: First running version. You can keep track of our progress here:

https://github.com/AltraMayor/gatekeeper/milestone/1

Once we finish our first milestone, Gatekeeper will have sharp edges that we intend to polish before releasing to a partner that is helping us with operational feedback. So our second milestone is to have a version ready for the first tests in production environments. You can keep track of this milestone here:

https://github.com/AltraMayor/gatekeeper/milestone/2

The goal of our third milestone is to implement the feedback we get from the production tests, and prepare a release for the first deployment:

https://github.com/AltraMayor/gatekeeper/milestone/3

We hope to see the first deployment to become operational sometime after June.

We'll keep this thread open and add updates from time to time, so you, and whoever becomes interested, can get a summary of our progress.

**Comment by AltraMayor** [comment]
We reached our first milestone today. We are way behind the schedule we've set to ourselves, but it does not mean that we have stalled. We have had to overcome lots of challenges. Although more challenges are likely to come, we're going to keep moving forward.

**Comment by AltraMayor** [comment]
We've reached our second milestone. From now on, all our efforts are going to focus on getting the first deployment of Gatekeeper in place.

**Comment by AltraMayor** [comment]
Today we released the first release candidate of version 1.0.0, not the final release. But we expect to see small changes from now on until the final release. In fact, we are going to use the RC1 to make the first deployment. It's from this first deployment that we expect to get most of the feedback for the final release.

We've also updated the wiki with documentation, the original motivation of this issue. While the current documentation might not be enough at this point, we intend to improve it as feedback and questions come in.
