### ISSUE TITLE
What exactly is Gatekeeper?

### ISSUE THREAD

**Issue by tr1xy** [AltraMayor/gatekeeper#405]
Can Gatekeeper compete with leading DDoS protections like Voxility and OVH SAS?

I doubt but I have to ask because I am jumping into server hosting :D

**Comment by AltraMayor** [comment]
Our group is still setting up the very first production deployment of Gatekeeper, so we cannot promise the end of DDoS yet. But we believe Gatekeeper is ready for production deployments with NICs up to 10Gbps. This 10Gbps-NIC limit is mostly because it has been the only hardware we had available for development, so we don't know how fast our code truly is at this point. Once the first deployment is done and we gain access to better hardware, we intend to pursue line speed on 100Gbps NICs.

The first deployments of Gatekeeper will likely complement protection services. For example, a company may need Gatekeeper to protect traffic coming from an Internet exchange because this traffic bypasses its protection provider (e.g. Voxility). Another example would be to protect origin servers behind Cloudflare, so attackers cannot bypass Cloudflare's HTTP protection. Gatekeeper can also be customized to address the protection needs of applications (e.g. games) that don't follow standard Internet protocols or have use cases that don't match well the way protection services work.

We do expect that Gatekeeper deployments will meet and eventually exceed the protection guarantees of services like the ones you've pointed out. But, even if Gatekeeper had all the bell and whistles today, it wouldn't be for everyone. For example, if a company has only 10 servers, it's likely better off hiring a protection provider due to the cost to add and maintain servers and bandwidth to deploy Gatekeeper.

Finally, we don't really compete with Voxility, OVH, and similar protection providers, but with the technologies that they use to implement their services. As the operational cost of Gatekeeper lower, these providers may become motivated to adopt Gatekeeper to lower their costs and explore the extras that Gatekeeper can offer. For example, although it has not been implemented yet, Gatekeeper will be extended to also work as a geographically distributed load balancer.

**Comment by tr1xy** [comment]
I can donate Voxility server if needed for testing purposes

**Comment by AltraMayor** [comment]
Thank you very much for your offer, @tr1xy. Once we are done with the first deployment, we'll start planning the next release of Gatekeeper and what we need to get there. Then, we'll be able to take on your offer.

We'll need to find funds for the hardware needed to make Gatekeeper work with 100Gbps NICs. It's not only about fancier NICs, but also a number of servers and switches for isolating measurements since that, at 100Gbps, interference in the caches of CPU cores can lead to misleading results.

**Comment by theraw** [comment]
@AltraMayor do Gatekeeper has any protection for UDP mostly servers that are used for gaming? can it somewhat filter traffic? and actually be able to stop the attacker even if stuff like `iptables ban` or `router ban` still couldn't stop the attack?

**Comment by AltraMayor** [comment]
Hi @theraw,

SHORT ANSWER: YES, YES, YES.

LONG ANSWER:

We don't have experience with gaming protocols, but Gatekeeper was designed to protect any protocol above IPv4 or IPv6. The requirement is that one has to write a policy that instructs the Gatekeeper deployment of how to protect those protocols. @cjdoucette is going to put his Ph.D. thesis upon the [Publications](https://github.com/AltraMayor/gatekeeper/wiki/Publications) page of our wiki soon; he's just waiting for the final format approval to have it published everywhere. His thesis presents how to write a policy from scratch. Watching his [defense](https://youtu.be/nDGnrv7kWa8) should give you a good idea of how Gatekeeper works.

If you want to dive into code to figure out how to write a policy, you should focus on the files in the folder `bpf` and the file [`policy.lua`](https://github.com/AltraMayor/gatekeeper/blob/master/lua/examples/policy.lua) in the repository.

**Comment by theraw** [comment]
@AltraMayor thanks for fast response 👏 

Even tho i don't have much idea about Lua i'll give this a try when i can and provide feedback if have.

**Comment by cjdoucette** [comment]
The thesis is now on the [Publications](https://github.com/AltraMayor/gatekeeper/wiki/Publications) page. Chapter 3 describes how to write destination policies.
