### ISSUE TITLE
Better install instructions.

### ISSUE THREAD

**Issue by dessalines** [AltraMayor/gatekeeper#406]
The install instructions should be a list of commands on the README. This had me navigating to several different pages, looking up how to extract this tar, etc.

**Comment by AltraMayor** [comment]
Would you care to submit a pull request for the README file?

**Comment by dessalines** [comment]
I couldn't get it to install properly in the first place, the dpkg commands failed.

**Comment by AltraMayor** [comment]
Please post the error messages.

**Comment by cjdoucette** [comment]
I just tested it, and the suggested `dpkg` command fails because:

- The version of Gatekeeper needs to be pattern matched correctly -- the README command specifically says `gatekeeper-1.0.0-0_amd64.deb` but the package is `gatekeeper_1.0.0~rc1-0_amd64.deb`.
- `gatekeeper-bird_2.0.4-0_amd64.deb` is listed in the README command but is not in the package.

**Comment by andrenth** [comment]
I've update the release tarball to include the `gatekeeper-bird` package. The installation instructions have been fixed and made version-independent in #407 .
