### ISSUE TITLE
Could you please make a video tutorial on setting up this tool with explantion 

### ISSUE THREAD

**Issue by FrankensteinEvil0069** [AltraMayor/gatekeeper#470]
Please make a youtube tutorial explaining how to set it up in ways you told in the description <br> Thanks !!!!

**Comment by AltraMayor** [comment]
Hi @FrankensteinEvil0069,

We will eventually have more content to help people to do their own deployments, but, for now, one has to be willing to dive into the content available on our wiki to get going. You find some presentations to get started with the concepts on the page [Publications](https://github.com/AltraMayor/gatekeeper/wiki/Publications). I recommend starting with [Cody's presentation](https://youtu.be/nDGnrv7kWa8).

Once you have a sense of how Gatekeeper works, you have two things to do: (1) setting up at least a Gatekeeper server, router(s), and a Grantor server, and (2) write a policy to be enforced. The [file `README.md`](https://github.com/AltraMayor/gatekeeper#readme) is a good starting point to set up Gatekeeper and Grantor servers. You should read Chapter 3 of Cody's Ph.D. thesis available on the Publications page (link above) and check out the examples available in the repository to write a policy that matches your environment.

@andrenth is planning to post on our wiki by the beginning of June, a write-up of his notes of the production deployment on which he's working. While his notes are going to be helpful for anyone planning a production deployment, It's not meant to describe everything because each deployment has unique demands from the locations where Gatekeeper servers are installed, different kinds of routers used, different applications to be protected, and particular network topology, size, and capacity. So it would be best if you didn't wait for it to get started.

We've applied to present our work at a couple of conferences this year, and we'll announce that on the home of our wiki once we receive the acceptances. We expect to eventually be able to post the videos of these presentations on our wiki. So you can keep an eye out for those announcements.

I understand that doing all of that to get started may feel daunting. However, you have to keep in mind that Gatekeeper is not a drop-in module installed on webservers but a whole system to deal with DDoS attacks at the infrastructure level. Therefore, even with more documentation, presentation, tutorials, and videos, it won't be as simples as installing webservers. Gatekeeper is designed to meet the need of organizations that already have a bunch of servers and routers.

**Comment by FrankensteinEvil0069** [comment]
Thanks for your kind response. <br> I have understood all your instructions and hopefully I will compliy them correctly.
