### ISSUE TITLE
Update Gatekeeper's DPDK to LTS 20.11.1

### ISSUE THREAD

**Issue by AltraMayor** [AltraMayor/gatekeeper#502]
The newest kernel of Ubuntu 20.04 LTS, version 5.5, has a not-identified issue with the current version of Gatekeeper's DPDK. So Gatekeeper's DPDK must be updated to LTS 20.11.1. Anyone facing this issue should stick to kernel version 5.4 while this issue is being addressed.

This issue depends on issue #431.

**Comment by mengxiang0811** [comment]
The DPDK branch [gatekeeper-dpdk](https://github.com/cjdoucette/dpdk/commits/gatekeeper-dpdk) will be used for the upgrade.

**Comment by mengxiang0811** [comment]
The patch [lib: allow load BPF from ELF files](https://github.com/cjdoucette/dpdk/commit/d96ba3c8568af6215872d0bdc06725783b2c2b55) was removed because the config file that contains `CONFIG_RTE_LIBRTE_BPF_ELF` has been removed in this [patch](https://github.com/cjdoucette/dpdk/commit/ec260aa3ad7ed1cc08e0af94f73c0509396ac989#diff-b79606fb3afea5bd1609ed40b622142f1c98125abcfe89a76a661b0e8e343910)

**Comment by AltraMayor** [comment]
Is the `libelf-dev` still needed? Or did they implement the code to read BPF from ELF files in DPDK? Or is DPDK using another lib to do this? This information is important to update the section [Install Dependencies](https://github.com/AltraMayor/gatekeeper#install-dependencies) of our README file and the dependencies of the Debian packages.

**Comment by mengxiang0811** [comment]
Just checked the current [implementation of bpf library](https://github.com/cjdoucette/dpdk/blob/dpdk_rebase/lib/librte_bpf/bpf_load_elf.c). Yes, `libelf-dev` is still needed (e.g., `elf_getscn()`).

**Comment by AltraMayor** [comment]
Pull request #538 closed this issue.
