### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by shirley04** [AltraMayor/gatekeeper#508]
run gatekeeper , report Segmentation fault (core dumped)

Device with port_id=0 already stopped
Device with port_id=1 already stopped
GATEKEEPER: net: cannot set the MTU on the front iface (error 95)
GATEKEEPER: net: failed to start Gatekeeper network

**Comment by AltraMayor** [comment]
It seems that the NICs you are using don't support the functionalities that Gatekeeper needs. What are the models of the NICs you are using? You can get some information about your NICs running the following script available in the repository: `dependencies/dpdk/usertools/dpdk-devbind.py --status-dev net`

**Comment by shirley04** [comment]
I have bounded 03:00.0 & 0b:00.0 to dpdk
dependencies/dpdk/usertools/dpdk-devbind.py --status-dev net

Network devices using DPDK-compatible driver
============================================
0000:03:00.0 'VMXNET3 Ethernet Controller 07b0' drv=uio_pci_generic unused=vmxnet3,igb_uio,vfio-pci
0000:0b:00.0 'VMXNET3 Ethernet Controller 07b0' drv=uio_pci_generic unused=vmxnet3,igb_uio,vfio-pci

Network devices using kernel driver
===================================
0000:13:00.0 'VMXNET3 Ethernet Controller 07b0' if=ens224 drv=vmxnet3 unused=igb_uio,vfio-pci,uio_pci_generic *Active*

**Comment by AltraMayor** [comment]
Hi @shirley04,

We have had a number of issues with virtual NICs. Since our current focus is on making sure that production deployments are supported, we are postponing the work of addressing these virtual NIC issues. We are well aware that this choice makes it harder to experiment with Gatekeeper. We'll eventually catch up to virtual NICs, but, at this point, I don't know when we'll start this work.

**Comment by AltraMayor** [comment]
You find the NICs that DPDK supports here: http://core.dpdk.org/supported/#nics
