### ISSUE TITLE
Failed to install v1.0.0 from packages

### ISSUE THREAD

**Issue by Whitefang2003** [AltraMayor/gatekeeper#545]
Hello,

I get this error when i try to build Gatekeeper with debian packages.
![immagine](https://user-images.githubusercontent.com/71386613/162442677-ec0695a8-21c2-414d-9f45-960d9e1ec026.png)
![immagine](https://user-images.githubusercontent.com/71386613/162442858-ed7abc35-28e9-4dfe-b292-dc9d4d9258e0.png)

OS: Ubuntu20.04

**Comment by AltraMayor** [comment]
Hi @Whitefang2003,

There're several things going on in your output.

1. You didn't include the command line(s) that produced your output. You say "when i try to build Gatekeeper", but the output suggests that you're installing Gatekeeper, not building it.
2. If you are installing Gatekeeper instead of building it, did you build these packages? Or are you installing the packages we made available with the release v1.0.0?
3. There must have been an error before the first one reported in the first image. Otherwise, there shouldn't exist file `/var/crash/gatekeeper-dpdk-rte-kni-dkms.0.crash` as reported in the error message `ERROR: Cannot create report: {Errno 17] File exists: '/var/crash/gatekeeper-dpdk-rte-kni-dkms.0.crash'`.
4. The second image reports that you already have package `dpdk` installed, so `dpkg` cannot install `gatekeeper-dpdk`. You need to remove the package `dpdk` with a command like `apt purge dpdk`. If you built those packages with Ubuntu's DPDK installed, there's a chance that you linked things against the wrong headers.

If you still know exactly the state that this installation, you may be able to fix the items above directly. If not, you're better off restarting the process fresh and keeping track of what's been done and what worked/failed.

**Comment by Whitefang2003** [comment]
Hello,

Yes sorry i mean to install** my bad

And i downloaded the latest release [v1.0.0)]

From this command i get the error "sudo dpkg -i libgkrte-*.deb \
    libgkdpdk-dev_*_amd64.deb \
    gatekeeper-dpdk_*_amd64.deb \
    gatekeeper-dpdk-dev_*_amd64.deb \
    gatekeeper-dpdk-igb-uio-dkms_*_amd64.deb \
    gatekeeper-dpdk-rte-kni-dkms_*_amd64.deb \
    gatekeeper-bird_*_amd64.deb \
    gatekeeper_*_amd64.deb"

"ERROR: Cannot create report: {Errno 17] File exists: '/var/crash/gatekeeper-dpdk-rte-kni-dkms.0.crash'" this error i get because i was trying 2 times to install it. But i get the same error even on a new machine.

But even i try to start gatekeeper with this error i get this error
![immagine](https://user-images.githubusercontent.com/71386613/162535008-9f81727d-a260-4274-884a-89430f5ea764.png)

**Comment by Whitefang2003** [comment]
Hi, @AltraMayor

I resolved the error with "signal"
But now i get a new error
![immagine](https://user-images.githubusercontent.com/71386613/162837024-9fe51dfe-3117-4859-8d72-33718dc7acea.png)

**Comment by AltraMayor** [comment]
Hi @Whitefang2003,

Could you document on this thread how you've been solving some of your problems? This will save someone else's time. Thank you in advance for this contribution.

Notice that you're reporting only the very step that's triggering issues, and not the steps you've done to get there, so someone trying to help has to guess how you got there. This is important because there's no easy way to check if you've skipped a step. For example, have you followed the steps on [section "Configure Gatekeeper"](https://github.com/AltraMayor/gatekeeper#configure-gatekeeper) of the README file?

Could you check the logs in `/var/log/gatekeeper`? The files there may have more information on what's going on.
