### ISSUE TITLE
What is the difference between GK_FWD_GATEWAY_FRONT_NET and GK_FWD_GATEWAY_BACK_NET

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#571]
GK_FWD_GATEWAY_FRONT_NET and GK_FWD_GATEWAY_BACK_NET
Is the difference between them taking different GK ports to GW?

**Comment by AltraMayor** [comment]
Yes, that is the difference.

It was an implementation choice. We could've followed the standard approach of having a single action and requiring the port information. This approach is better when the number of ports can vary. Given that the ports' number and purpose are fixed in Gatekeeper, having different actions was simpler and enough.
