### ISSUE TITLE
syn flood to 300mbps，lpm: IPv4 lookup miss for

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#578]
At present, I tested to initiate a syn flood. When the attack reached 300m, there were a lot of "lpm: IPv4 lookup miss for x.x.x.x" miss source addresses.Occasionally an lpm miss when attacking below 300mbps

**Comment by ShawnLeung87** [comment]
> Do the missed IPv4 addresses belong to protected prefixes (i.e. Grantor FIB entries on Gatekeeper servers)? If not, could you explain what the missed addresses are in your environment?
This miss ip addr is the ip that launched the ddoos attack

**Comment by AltraMayor** [comment]
Given that the missed address is a source address, I assume you've found those log entries on a Grantor server. In this case, you can safely ignore those log entries since they're just informing you that the address is not in the LPM table you're using in your policy. In production, you could use that information to check if you should update the LPM table.

If you don't find those log entries helpful, you can disable them by lowering the log level. They are only logged when the log level is `DEBUG`. See the recommendation for log level in production in [Section "Other functional blocks"](https://github.com/AltraMayor/gatekeeper/wiki/Tips-for-Deployments#other-functional-blocks-1) of the wiki page "Tips for Deployments".
