### ISSUE TITLE
n_gk_lcores can only be configured with 4

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#595]
Stable version 1.0.0

n_gk_lcores can only be configured with 4, more than 4 reports

"EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list"

CPU:Intel(R) Xeon(R) Platinum 8280M CPU @ 2.60GHz  cpu cores  28 ,numa 2
RAM :384G
Hupag default_hugepagesz=1G hugepagesz=1G hugepages=360

**Comment by AltraMayor** [comment]
I guess your RAM is DDR4. If so, not being able to have more than 4 instances of the GK block may be fine. Four instances of the GK block on a mainboard with 2 NUMA nodes may already be at the limit of the memory buses. If so, having more instances will slow everything down because they would overload the memory buses.

If you, however, want to proceed anyway, reduce the size of your flow table (parameter `flow_ht_size`) and the size of your FIB (parameters `max_num_ipv4_rules`, `num_ipv4_tbl8s`, `max_num_ipv6_rules`, and `num_ipv6_tbl8s`) in the file `lua/gk.lua`. [The example values](https://github.com/AltraMayor/gatekeeper/blob/master/lua/gk.lua) found in the repository would be a good start.
