### ISSUE TITLE
No GK block allocated for Gatekeeper server

### ISSUE THREAD

**Issue by pjain17** [AltraMayor/gatekeeper#627]
Hello,
I am trying to run Gatekeeper on an ESXi instance (ubuntu 22.04, kernel - 5.15.0-58-generic).
When i run gatekeeper.. i see 
```
root@gatekeeper:/home/ciscoadmin/gatekeeper# ./gatekeeper
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL:   Invalid NUMA socket, default to 0
EAL:   using IOMMU type 1 (Type 1)
EAL: Ignore mapping IO port bar(3)
EAL: Probe PCI driver: net_vmxnet3 (15ad:7b0) device: 0000:03:00.0 (socket 0)
EAL:   Invalid NUMA socket, default to 0
EAL: Ignore mapping IO port bar(3)
EAL: Probe PCI driver: net_vmxnet3 (15ad:7b0) device: 0000:0b:00.0 (socket 0)
EAL:   Invalid NUMA socket, default to 0
EAL: No legacy callbacks, legacy socket not created
EAL: See files in . for further log
```
and the logs show
```
Main/0: cycles/second = 2095078930, cycles/millisecond = 2095078, picosec/cycle = 477
Main/0: config: ./lua/main_config.lua:48: No GK block allocated for Gatekeeper server
Main/0: Failed to configure Gatekeeper
```
I am not sure what other config changes need to be made. Could you point me in the right direction?

**Comment by pjain17** [comment]
Also, have you guys ever tried to run gatekeeper as a container/K8s pod ?

**Comment by AltraMayor** [comment]
Hi @pjain17,

```
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
```
You need 9 cores in the instance: 8 for Gatekeeper and 1 for the kernel. Check out the section [CPU](https://github.com/AltraMayor/gatekeeper/wiki/Hardware-Requirements#cpu) on the page Hardware Requirements of our wiki for an explanation.

```
EAL: No available hugepages reported in hugepages-1048576kB
```
If you have set up hugepages-2048kB, this message is okay. Otherwise, go through the section [How to Set Up](https://github.com/AltraMayor/gatekeeper#how-to-set-up) on the README.md file.

**Comment by AltraMayor** [comment]
> Also, have you guys ever tried to run gatekeeper as a container/K8s pod ?

No.

We have tried to use virtualization in the past to help with the development, testing, and evaluation. But, after running into some issues that were only pertinent to virtualized environments, we moved on to work with real machines. Most of the problems revolved around what a virtual NIC can actually do. For example, no virtual NIC in DPDK supported configuring RSS at the time; even ENA failed to do so despite its driver saying otherwise.

We know virtualization has improved a lot since then and that it might be possible to run Gatekeeper reasonably well nowadays. But, given that all deployers that support our project are focused on real machines and wish for even higher processing performance to lower operational costs while meeting the peaking capacity of DDoS attacks, our focus is still on real machines and more capable NICs.

**Comment by pjain17** [comment]
Thank you for your response. That was helpful. I am now encountering the below issue

**Comment by pjain17** [comment]
thank you for your response. That was helpful.
Now i am running into another issue, regarding loading of the bpf program
```
root@gatekeeper:/home/ciscoadmin/gatekeeper# cat gatekeeper_2023_01_17_19_29.log
Main/0: cycles/second = 2095078683, cycles/millisecond = 2095078, picosec/cycle = 477
rte_bpf_elf_load() is not supported with current config
rebuild with libelf installed
Main/0: gk_load_bpf_flow_handler(): file "./lua/bpf/granted.bpf" does not have the BPF program "init"; rte_errno = 95: Operation not supported
Main/0: config: ./lua/gk.lua:108: Failed to load BPF program: ./lua/bpf/granted.bpf
Main/0: Failed to configure Gatekeeper
```
I did install libelf and built the code again, but i still see this issue.

**Comment by AltraMayor** [comment]
```
rte_bpf_elf_load() is not supported with current config
rebuild with libelf installed
```
It seems that you built DPDK **before** installing `libelf`, so the configuration system identified that `libelf` was unavailable and used the stub version of `rte_bpf_elf_load()` in file `dependencies/dpdk/lib/librte_bpf/bpf_load.c`. If you have not changed the configuration of DPDK before rebuilding it, the building system will continue to use the previous configuration, which ignores `libelf`. You can test this hypothesis with the command `grep RTE_LIBRTE_BPF_ELF dependencies/dpdk/build/rte_build_config.h` while in the folder of Gatekeeper; the output shows `#define RTE_LIBRTE_BPF_ELF 1` when `libelf` is being used.

**Comment by paridhi1790** [comment]
thank you! that worked.. i see this new error:

**Comment by AltraMayor** [comment]
According to the log entry below, your front NIC is having trouble with multiple queues.
```
Main/0: configure_queue(): failed to configure RX queue 1 of port 0 of interface front (errno=22): Invalid argument
```
The root cause is not reported in the log entries. But, given that the log entries report that your front NIC does not support RSS, the most likely root cause is that your NIC does not support multiple queues. So Gatekeeper cannot run on your setup at this time.
