### ISSUE TITLE
Running gatekeeper and grantor on the same server

### ISSUE THREAD

**Issue by arvindin** [AltraMayor/gatekeeper#665]
We have a simple demo setup on a server with gatekeeper, can we run grantor and gatekeeper on the same server.
We modified the deployment diagram in the Wiki, please find attached, is this Ok? Need validation to move forward.

Thanks
[Deployment diagram.pdf](https://github.com/AltraMayor/gatekeeper/files/13552328/Deployment.diagram.pdf)

**Comment by AltraMayor** [comment]
Unless you have a solid motivation to run a Grantor server on the same server you run your Gatekeeper server, you will save a lot of time not going down this path. That setup has a lot of problems to overcome because Gatekeeper/DPDK accesses the hardware directly. This direct access enables Gatekeeper to do more with fewer resources, but it creates several problems in situations you're considering.
