### ISSUE TITLE
Please provide a gatekeeper-log-exporter deployment document

### ISSUE THREAD

**Issue by ShawnLeung87** [AltraMayor/gatekeeper#710]
Can you provide a gatekeeper-log-exporter configuration document? There is no detailed parameter modification reference under the gatekeeper-log-exporter project. At present, after I compile and run the program, gatekeeper-log-exporter does not process any log content.

**Comment by AltraMayor** [comment]
I cannot. I'm not involved with the [Gatekeeper Log Exporter](https://github.com/hostnetbr/gatekeeper-log-exporter) project, nor have I used it. A Gatekeeper deployer has developed and has been maintaining that project. Although I expect they will eventually add more documentation, it won't be soon since they have been busy with their [Gatekeeper Consultancy](https://www.digirati.com.br/en/gatekeeper-consultancy/) that started last month. If you cannot wait for the documentation, consider signing up for their consultancy.

**Comment by ShawnLeung87** [comment]
OK, I will study this log exporter written in Go language again. If it still doesn’t work, I will rewrite a log exporter in Python for data analysis.

**Comment by ShawnLeung87** [comment]
We use other tools to implement this feature. Close this ticket
